### ISSUE TITLE
[依頼]最終課題挙動確認

### ISSUE THREAD

**Issue by kuromon11** [kuromon11/freemarket_sample_71f#68]
■ URL
IPアドレス：http://52.196.62.187
Github（最終課題のリポジトリ）：https://github.com/kuromon11/freemarket_sample_71f

■ Basic認証
ID：tech
Pass：camp

■ テスト用アカウント
◯ 購入者用
メールアドレス：buyer@buyer
パスワード：testtest

◯ 購入用カード情報
番号：4242424242424242
期限：12月/20年
セキュリティカード：123

◯ 出品者用
メールアドレス：seller@seller
パスワード：testtest

**Comment by yasunamiura** [comment]
ご提出ありがとうございます！
確認させて頂きましたが、修正箇所ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！
